CREATE TABLE USR_FITNESS.MEMBROS (
    MEMBRO_ID NUMBER NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    DATA_NASCIMENTO DATE,
    TELEFONE VARCHAR2(15),
    EMAIL VARCHAR2(100),
    CONSTRAINT PK_MEMBROS PRIMARY KEY (MEMBRO_ID)
);

CREATE TABLE USR_FITNESS.PLANOS_TREINAMENTO (
    PLANO_ID NUMBER NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    DESCRICAO CLOB,
    DURACAO_SEMANAS NUMBER,
    CONSTRAINT PK_PLANOS PRIMARY KEY (PLANO_ID)
);

CREATE TABLE USR_FITNESS.EXERCICIOS (
    EXERCICIO_ID NUMBER NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    TIPO VARCHAR2(50),
    DESCRICAO CLOB,
    CONSTRAINT PK_EXERCICIOS PRIMARY KEY (EXERCICIO_ID)
);

CREATE TABLE USR_FITNESS.HISTORICO_TREINAMENTO (
    HISTORICO_ID NUMBER NOT NULL,
    MEMBRO_ID NUMBER NOT NULL,
    PLANO_ID NUMBER NOT NULL,
    DATA_INICIO DATE,
    DATA_FIM DATE,
    STATUS VARCHAR2(50),
    CONSTRAINT PK_HISTORICO PRIMARY KEY (HISTORICO_ID),
    CONSTRAINT FK_HISTORICO_MEMBRO FOREIGN KEY (MEMBRO_ID) 
        REFERENCES USR_FITNESS.MEMBROS(MEMBRO_ID),
    CONSTRAINT FK_HISTORICO_PLANO FOREIGN KEY (PLANO_ID) 
        REFERENCES USR_FITNESS.PLANOS_TREINAMENTO(PLANO_ID)
);

CREATE TABLE USR_FITNESS.ROTINAS_TREINAMENTO (
    ROTINA_ID NUMBER NOT NULL,
    PLANO_ID NUMBER NOT NULL,
    EXERCICIO_ID NUMBER NOT NULL,
    SERIES NUMBER,
    REPETICOES NUMBER,
    DESCANSO_SEGUNDOS NUMBER,
    CONSTRAINT PK_ROTINAS PRIMARY KEY (ROTINA_ID),
    CONSTRAINT FK_ROTINA_PLANO FOREIGN KEY (PLANO_ID) 
        REFERENCES USR_FITNESS.PLANOS_TREINAMENTO(PLANO_ID),
    CONSTRAINT FK_ROTINA_EXERCICIO FOREIGN KEY (EXERCICIO_ID) 
        REFERENCES USR_FITNESS.EXERCICIOS(EXERCICIO_ID)
);

CREATE SEQUENCE USR_FITNESS.SEQ_MEMBRO_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE USR_FITNESS.SEQ_PLANO_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE USR_FITNESS.SEQ_EXERCICIO_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE USR_FITNESS.SEQ_HISTORICO_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE USR_FITNESS.SEQ_ROTINA_ID START WITH 1 INCREMENT BY 1;
